-- MySQL Script generated by MySQL Workbench
-- Wed Mar 18 17:56:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gocellar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gocellar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gocellar` ;
USE `gocellar` ;

-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_advertisement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_advertisement` (
  `id` INT NOT NULL,
  `create_time` DATE NULL,
  `link_url` VARCHAR(255) NULL,
  `title` VARCHAR(255) NULL,
  `maximum_population` INT NULL,
  `eventDate` DATE NULL,
  `startPeriod` DATE NULL,
  `endPeriod` DATE NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_task` (
  `id` INT NOT NULL,
  `createTime` DATE NULL,
  `title` VARCHAR(255) NULL,
  `taskDetail` TEXT NULL,
  `creator` BIGINT(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_awardCredit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_awardCredit` (
  `id` INT NOT NULL,
  `userId` INT NULL,
  `amount` DECIMAL(19,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_user` (
  `id` BIGINT(255) NOT NULL,
  `creat_time` DATE NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `phone_number` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `status` TINYINT(4) NULL DEFAULT NULL,
  `update_time` BIGINT(20) NULL DEFAULT NULL,
  `briefDescription` TEXT NULL DEFAULT NULL,
  `accessToken` VARCHAR(255) NULL DEFAULT NULL,
  `refreshToken` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `awardCreditId` INT(11) NULL DEFAULT NULL,
  `roleId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `awardCredit_idx` (`awardCreditId` ASC),
  CONSTRAINT `awardCredit`
    FOREIGN KEY (`awardCreditId`)
    REFERENCES `gocellar`.`gocellar_awardCredit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_winery_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_winery_info` (
  `id` INT(11) NOT NULL,
  `wineryName` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `state` VARCHAR(255) NULL,
  `postCode` VARCHAR(255) NULL,
  `establishedTime` INT(5) NULL,
  `description` TEXT NULL,
  `websiteUrl` VARCHAR(255) NULL,
  `wineProduction` VARCHAR(255) NULL,
  `plantArea` VARCHAR(255) NULL,
  `haveCellarDoor` BINARY NULL,
  `cellarDoorOpeningHours` VARCHAR(255) NULL,
  `businessHours` VARCHAR(255) NULL,
  `ownerName` VARCHAR(255) NULL,
  `wineMakerName` VARCHAR(255) NULL,
  `ABN` VARCHAR(255) NULL,
  `ACN` VARCHAR(255) NULL,
  `telephone` VARCHAR(255) NULL,
  `mobilePhone` VARCHAR(255) NULL,
  `Fax` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `insuranceProvided` BINARY NULL,
  `wineryImage` VARCHAR(45) NULL,
  `logoImage` VARCHAR(45) NULL,
  `otherDocsImage` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_supplier` (
  `userId` BIGINT(20) NOT NULL,
  `permissionId` INT(11) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `gocellar_winery_info_id` INT(11) NOT NULL,
  PRIMARY KEY (`userId`),
  INDEX `winery_info_idx` (`permissionId` ASC),
  CONSTRAINT `winery_info`
    FOREIGN KEY (`permissionId`)
    REFERENCES `gocellar`.`gocellar_winery_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_internalUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_internalUser` (
  `userId` BIGINT(20) NOT NULL,
  `permissionId` INT(11) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`userId`));


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_buyer` (
  `id` INT(11) NOT NULL,
  `isVIP` BINARY(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_chatRoom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_chatRoom` (
  `id` INT NOT NULL,
  `createTIme` DATE NULL,
  `creatorMsg` TEXT NULL,
  `receiverMsg` TEXT NULL,
  `creator` BIGINT(20) NULL,
  `receiver` BIGINT(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_coupon` (
  `id` INT(11) NOT NULL,
  `amount` INT(11) NULL,
  `create_time` DATE NULL,
  `expire_end_date` DATE NULL,
  `expire_start_date` DATE NULL,
  `name` VARCHAR(255) NULL,
  `quantity` INT(11) NULL,
  `send_end_time` DATE NULL,
  `send_start_time` DATE NULL,
  `order_coupon_id` INT(11) NULL,
  `sender_id` BIGINT(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_user_coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_user_coupon` (
  `quantiy` INT(11) NOT NULL,
  `coupon_id` INT(11) NULL,
  `user_id` BIGINT(20) NULL,
  PRIMARY KEY (`quantiy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_city` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NULL,
  `state_id` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_state` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NULL,
  `country_id` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_country` (
  `id` INT(11) NOT NULL,
  `code` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_address` (
  `id` BIGINT(20) NOT NULL,
  `addressAlias` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `create_time` DATE NULL,
  `phone_number` VARCHAR(255) NULL,
  `post_code` VARCHAR(255) NULL,
  `receiver` VARCHAR(255) NULL,
  `update_time` DATE NULL,
  `city_id` INT(11) NULL,
  `country_id` INT(11) NULL,
  `state_id` INT(11) NULL,
  `user_id` BIGINT(20) NULL,
  INDEX `city_idx` (`city_id` ASC),
  INDEX `state_idx` (`state_id` ASC),
  INDEX `country_idx` (`country_id` ASC),
  INDEX `userId_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `city`
    FOREIGN KEY (`city_id`)
    REFERENCES `gocellar`.`gocellar_city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `state`
    FOREIGN KEY (`state_id`)
    REFERENCES `gocellar`.`gocellar_state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `country`
    FOREIGN KEY (`country_id`)
    REFERENCES `gocellar`.`gocellar_country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userId`
    FOREIGN KEY (`user_id`)
    REFERENCES `gocellar`.`gocellar_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_ship_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_ship_info` (
  `id` INT(11) NOT NULL,
  `create_time` DATE NULL,
  `name` VARCHAR(255) NULL,
  `price` DECIMAL(19,2) NULL,
  `ship_no` VARCHAR(255) NULL,
  `address_id` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `address_idx` (`address_id` ASC),
  CONSTRAINT `address`
    FOREIGN KEY (`address_id`)
    REFERENCES `gocellar`.`gocellar_address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_order_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_order_payment` (
  `id` BIGINT(20) NOT NULL,
  `cancel_time` DATE NULL,
  `create_time` DATE NULL,
  `payment` DECIMAL(19,2) NULL,
  `payment_gateway_no` VARCHAR(255) NULL,
  `payment_no` VARCHAR(255) NULL,
  `payment_type` TINYINT(4) NULL,
  `status` TINYINT(4) NULL,
  `description` TEXT NULL,
  `order_id` BIGINT(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_order` (
  `id` BIGINT(20) NOT NULL,
  `receive_time` DATE NULL,
  `confirmed_time` DATE NULL,
  `shipping_time` DATE NULL,
  `complete_time` DATE NULL,
  `invocie_title` VARCHAR(255) NULL,
  `ship_no` VARCHAR(255) NULL,
  `payment` DECIMAL(19,2) NULL,
  `status` TINYINT(4) NULL,
  `update_time` BIGINT(20) NULL,
  `gocellar_supplier_userId` BIGINT(20) NULL,
  `buyer_ship_info_id` INT(11) NULL,
  `supplier_id` BIGINT(20) NULL,
  `paymentId` BIGINT(20) NULL,
  `gocellar_buyer_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ship_info_idx` (`buyer_ship_info_id` ASC),
  INDEX `payment_idx` (`paymentId` ASC),
  INDEX `fk_gocellar_order_gocellar_buyer1_idx` (`gocellar_buyer_id` ASC),
  INDEX `fk_gocellar_order_gocellar_supplier1_idx` (`supplier_id` ASC),
  CONSTRAINT `ship_info`
    FOREIGN KEY (`buyer_ship_info_id`)
    REFERENCES `gocellar`.`gocellar_ship_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `payment`
    FOREIGN KEY (`paymentId`)
    REFERENCES `gocellar`.`gocellar_order_payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `buyer2`
    FOREIGN KEY (`gocellar_buyer_id`)
    REFERENCES `gocellar`.`gocellar_buyer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `supplier`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `gocellar`.`gocellar_supplier` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_order_coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_order_coupon` (
  `coupon_id` INT(11) NULL,
  `order_id` BIGINT(20) NULL,
  `user_id` BIGINT(20) NULL,
  INDEX `order_id_idx` (`order_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `coupon_id_idx` (`coupon_id` ASC),
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `gocellar`.`gocellar_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `gocellar`.`gocellar_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `coupon_id`
    FOREIGN KEY (`coupon_id`)
    REFERENCES `gocellar`.`gocellar_coupon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_category` (
  `id` INT(11) NOT NULL,
  `create_time` DATE NULL,
  `categoryName` VARCHAR(255) NULL,
  `parent_id` INT(11) NULL,
  `update_time` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_category_coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_category_coupon` (
  `coupon_id` INT(11) NULL,
  `category_id` INT(11) NULL,
  INDEX `category_idx` (`category_id` ASC),
  CONSTRAINT ` coupon`
    FOREIGN KEY (`coupon_id`)
    REFERENCES `gocellar`.`gocellar_coupon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category3`
    FOREIGN KEY (`category_id`)
    REFERENCES `gocellar`.`gocellar_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_brand` (
  `id` INT(11) NOT NULL,
  `description` TEXT NULL,
  `brandName` VARCHAR(255) NULL,
  `url` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_food_pairing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_food_pairing` (
  `id` INT(11) NOT NULL,
  `product_id` INT(11) NULL,
  `food_id` INT(11) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_product` (
  `id` INT(11) NOT NULL,
  `code` VARCHAR(255) NULL,
  `saled_quantity` INT(11) NULL,
  `create_time` TIME NULL,
  `description` VARCHAR(255) NULL,
  `volume` INT(11) NULL,
  `productName` VARCHAR(255) NULL,
  `original_price` DECIMAL(19,2) NULL,
  `sale_price` DECIMAL(20) NULL,
  `package` TINYINT(4) NULL,
  `status` TINYINT(4) NULL,
  `stock` INT(11) NULL,
  `sub_title` VARCHAR(255) NULL,
  `update_time` TIME NULL,
  `video_url` VARCHAR(1100) NULL,
  `weight` INT(11) NULL,
  `vintage` INT(11) NULL,
  `state` VARCHAR(255) NULL,
  `sight_score` INT(3) NULL,
  `nose_score` INT(7) NULL,
  `palate_score` INT(10) NULL,
  `product_code` VARCHAR(255) NULL,
  `threshold` INT(11) NULL,
  `alchohols` DECIMAL(2) NULL,
  `standard_drink` INT(11) NULL,
  `gocellar_food_pairing_id` INT NOT NULL,
  `winemaker` TEXT NULL,
  `brand_id` INT(11) NULL,
  `category_id` INT(11) NULL,
  `GrapeType_id` INT(11) NULL,
  `creator_user_id` BIGINT(20) NULL,
  `updator_user_id` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `brand_idx` (`brand_id` ASC),
  INDEX `category_idx` (`category_id` ASC),
  INDEX `fk_gocellar_product_gocellar_food_pairing1_idx` (`gocellar_food_pairing_id` ASC),
  CONSTRAINT `brand`
    FOREIGN KEY (`brand_id`)
    REFERENCES `gocellar`.`gocellar_brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `gocellar`.`gocellar_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gocellar_product_gocellar_food_pairing1`
    FOREIGN KEY (`gocellar_food_pairing_id`)
    REFERENCES `gocellar`.`gocellar_food_pairing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_category_porduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_category_porduct` (
  `category_id` INT(11) NULL,
  `product_id` INT(11) NULL,
  INDEX `product_idx` (`product_id` ASC),
  CONSTRAINT `category2`
    FOREIGN KEY (`category_id`)
    REFERENCES `gocellar`.`gocellar_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product2`
    FOREIGN KEY (`product_id`)
    REFERENCES `gocellar`.`gocellar_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_product_picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_product_picture` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NULL,
  `url` VARCHAR(255) NULL,
  `product` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_scanning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_scanning` (
  `id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_product_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_product_comment` (
  `id` INT(11) NOT NULL,
  `create_time` DATE NULL,
  `description` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `star` TINYINT(4) NULL,
  `status` TINYINT(4) NULL,
  `order_item_id` BIGINT(20) NULL,
  `product_id` INT(11) NULL,
  `user_id` BIGINT(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_order_item` (
  `id` BIGINT(20) NOT NULL,
  `current_unit_price` DECIMAL(19,2) NULL,
  `quantity` INT(11) NULL,
  `status` TINYINT(4) NULL,
  `total_price` DECIMAL(19,2) NULL,
  `order_id` BIGINT(20) NULL,
  `product_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `order_idx` (`order_id` ASC),
  INDEX `product_idx` (`product_id` ASC),
  CONSTRAINT `order`
    FOREIGN KEY (`order_id`)
    REFERENCES `gocellar`.`gocellar_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product4`
    FOREIGN KEY (`product_id`)
    REFERENCES `gocellar`.`gocellar_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocellar`.`gocellar_environment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocellar`.`gocellar_environment` (
  `id` INT(11) NOT NULL,
  `app_version` VARCHAR(255) NULL,
  `crypto_key` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
